/* The road: the campaign's chapters, its acts, what is said after the war,
   and the cities along the way. Loaded after maps.js. */
const CAMPAIGN = [
  {
    objective: { type: 'rout' },
    id: 'ch1', title: 'Ambush on the Verdant Road', map: 'verdant',
    camp: [
      'Garret: "Four of us, and a road nobody holds. Your father would have called that an opportunity."',
      'Rowan: "My father is why there are four of us."',
      'Bram, from the top of the wagon: "Riders on the road. Bandits, by the way they sit. They have not seen us."',
    ],
    intro: [
      'Elderon bleeds. Two princes claim one crown, and the roads between their armies belong to no one.',
      'Rowan Aldric, youngest son of a house that chose the wrong prince, rides north with his few remaining companions.',
      'Bandits watch the Verdant Road. They do not know whose colors Rowan wears. They do not care.',
      '"Mira, stay behind Garret. Bram, take the high ground. If they want a fight, we give them one."',
      'Bram is already climbing. "Three of them. Do we get paid for this, or is it another of the honourable kind?"',
    ],
    enemies: [
      { job: 'squire', level: 1, x: 8, y: 2, name: 'Bandit' },
      { job: 'squire', level: 1, x: 9, y: 4, name: 'Bandit' },
      { job: 'archer', level: 1, x: 9, y: 1, name: 'Bandit Archer' },
    ],
    gil: 3100,
    outro: [
      'The bandits scatter into the hills. One of them was carrying coin newer than any bandit should have: milled edges, and a cog stamped on the face.',
      'Rowan pockets it and looks north, where smoke rises over Millbrook.',
    ],
  },
  {
    objective: { type: 'rout' },
    id: 'ch2', title: 'The Wolves of Millbrook', map: 'millbrook',
    camp: [
      'Mira: "The mill was still turning when I passed this way in spring. Someone should have shut it off."',
      'Garret: "Someone should have. Nobody did. That is the whole war in a sentence."',
    ],
    intro: [
      'Millbrook has been abandoned. Its mill wheel turns for no one.',
      'Goblins nest in the mill now, and their wolves have found the scent of travelers on the bridge.',
      '"Hold the bridge," Garret says. "Let them come to us one at a time."',
      'Mira counts her potions twice. "And nobody gets bitten. I have four of these, and I am not wasting one on Bram being brave."',
    ],
    enemies: [
      { job: 'goblin', level: 2, x: 2, y: 1 },
      { job: 'goblin', level: 2, x: 9, y: 1 },
      { job: 'wolf', level: 2, x: 6, y: 0 },
      { job: 'wolf', level: 2, x: 4, y: 2 },
    ],
    gil: 1600,
    recruit: { name: 'Lysa', job: 'chemist', level: 2 },
    outro: [
      'In the mill, a young woman hides among the sacks with a satchel of potions and a look of pure defiance.',
      '"Lysa," she says. "I was the village apothecary. There is no village any more, so I suppose I am yours."',
      'Lysa the Chemist joins the party!',
    ],
  },
  {
    objective: { type: 'rout', protectLeader: true },
    id: 'ch3', title: 'Hollowmere Ruins', map: 'hollowmere',
    camp: [
      'Lysa: "Deserters, at the temple. Aldous stopped paying his levies in autumn. He did not stop asking them to die."',
      'Rowan: "Then some of them may listen before they draw."  Garret: "Some. Keep your hand on the hilt for the others."',
    ],
    intro: [
      'The ruins of Hollowmere were a temple once. Now they shelter deserters from Prince Aldous\'s army.',
      'Deserters with steel and training, who have decided the Aldric name is worth a bounty.',
      '"They hold the high ground in the center," Mira warns. "Take the flanks first."',
    ],
    enemies: [
      { job: 'knight', level: 3, x: 5, y: 5, name: 'Deserter Knight' },
      { job: 'archer', level: 3, x: 6, y: 5, name: 'Deserter Archer' },
      { job: 'chemist', level: 2, x: 2, y: 1, name: 'Deserter Medic' },
      { job: 'squire', level: 2, x: 9, y: 1, name: 'Deserter' },
    ],
    gil: 1600,
    recruit: { name: 'Kael', job: 'archer', level: 3 },
    outro: [
      'One of the deserters throws down his bow and kneels. "I served your father at Redwater. I would rather serve his son than a prince who leaves his own men to starve."',
      'Kael the Archer joins the party!',
    ],
  },
  {
    objective: { type: 'rout', protectLeader: true },
    id: 'ch4', title: 'Sable Marsh', map: 'sable',
    camp: [
      'Bram: "A coven. Actual witches. Do they know we are coming?"  Lysa: "They were paid to know. That is the part I do not like."',
      'Kael tests his bowstring. "Paid by whom is the only question worth the marsh."',
    ],
    intro: [
      'The marsh road is the only way east that avoids the royal checkpoints.',
      'It is also where the Sable Coven trades curses for coin, and someone has paid them handsomely.',
      '"Mages," Lysa says. "Their spells take time to charge. Close the distance before they finish."',
      '"And mind the lights over the water, and whatever that is standing in the reeds. Neither is a tree."',
    ],
    enemies: [
      { job: 'blackMage', level: 4, x: 4, y: 3, name: 'Coven Mage' },
      { job: 'wisp', level: 4, x: 5, y: 6 },
      { job: 'treant', level: 4, x: 3, y: 8 },
      { job: 'thief', level: 4, x: 3, y: 5, name: 'Coven Cutpurse' },
      { job: 'wolf', level: 4, x: 7, y: 2 },
    ],
    gil: 2100,
    outro: [
      'The last mage sinks beneath the black water. On her body: a sealed letter bearing the crest of Ser Brannoc, Captain of Dunmarch.',
      'Beneath his seal, a second one Rowan does not know. A cog inside a circle. The same mark as the bandit\'s coin.',
    ],
  },
  {
    objective: { type: 'survive', rounds: 4, protectLeader: true },
    id: 'ch5', title: 'The Gates of Dunmarch', map: 'dunmarch',
    camp: [
      'Rowan: "Brannoc taught me the sword. He stood at my mother\'s funeral."',
      'Garret: "He stood at Redwater too, on the wrong side of the line, and I have not forgiven him that either. It does not have to be personal to be necessary."',
      'Mira: "It will be personal. Just make it quick."',
    ],
    intro: [
      'Ser Brannoc was Rowan\'s father\'s sworn brother. Now he hunts the Aldric line for Prince Aldous.',
      'His garrison holds the gate of Dunmarch. Archers on the wall, knights in the courtyard.',
      '"We do not need to take the keep," Rowan says. "Only the gate. Then we make Brannoc answer for that letter."',
    ],
    enemies: [
      { job: 'knight', level: 5, x: 5, y: 5, name: 'Gate Knight' },
      { job: 'knight', level: 4, x: 6, y: 6, name: 'Gate Knight' },
      { job: 'archer', level: 5, x: 3, y: 2, name: 'Wall Archer' },
      { job: 'archer', level: 5, x: 8, y: 2, name: 'Wall Archer' },
      { job: 'whiteMage', level: 5, x: 6, y: 3, name: 'Garrison Priest' },
    ],
    gil: 2700,
    recruit: { name: 'Tamsin', job: 'whiteMage', level: 5 },
    outro: [
      'The garrison priest lowers her staff. "Brannoc rode for Thornwall at dawn. He fears you, Aldric. He fears what your father knew."',
      '"Then I will heal your wounded on the way. I am done taking his orders."',
      'Tamsin the White Mage joins the party!',
    ],
  },
  {
    objective: { type: 'rout', protectLeader: true },
    id: 'ch6', title: 'Ashen Ridge', map: 'ashen',
    camp: [
      'Tamsin: "The ridge breathes. When it breathes out, the bombs drift up. When it breathes in, they come down where you are standing."',
      'Kael: "So we climb between breaths."  Tamsin: "So we climb between breaths."',
    ],
    intro: [
      'The road to Thornwall climbs the Ashen Ridge, where the old volcano still breathes.',
      'Bombs drift between the vents. Goblins have learned to herd them toward travelers.',
      '"Do not let the bombs get close," Kael warns. "When they are hurt, they explode."',
    ],
    enemies: [
      { job: 'bomb', level: 6, x: 3, y: 3 },
      { job: 'bomb', level: 6, x: 6, y: 2 },
      { job: 'bomb', level: 6, x: 2, y: 6 },
      { job: 'goblin', level: 6, x: 1, y: 1 },
      { job: 'goblin', level: 6, x: 5, y: 5 },
      { job: 'monk', level: 6, x: 0, y: 3, name: 'Ridge Hermit' },
    ],
    gil: 1200,
    outro: [
      'Below the ridge, Thornwall Cathedral rises from the fog. A single black banner hangs from its spire.',
      'Kael studies the goblins\' camp. "They were paid to herd the bombs at us. Paid in the same coin." He holds one up. The cog catches the light.',
    ],
  },
  {
    objective: { type: 'boss', protectLeader: true },
    id: 'ch7', title: 'Thornwall Cathedral', map: 'thornwall',
    camp: [
      'Nobody sleeps. Bram sharpens a blade that is already sharp. Lysa counts potions in the dark.',
      'Rowan: "Whatever he says at the altar, do not listen. He was always better at talking than I am."',
      'Garret: "Then let him talk, and hit him while he does."',
    ],
    intro: [
      'Ser Brannoc waits at the altar in armor that has forgotten its colors.',
      '"Your father learned that the princes are puppets, boy. That the war is a harvest. He would have told the realm."',
      '"So I killed him. And now I will kill you, and Elderon can go on burning in peace."',
      'Behind him, two suits of armour rise from the flagstones with nothing living inside them.',
      'Rowan draws his sword. "Not today, Ser."',
    ],
    enemies: [
      { job: 'darkKnight', level: 9, x: 6, y: 3, name: 'Ser Brannoc', boss: true,
        passives: ['counter', 'attackUp', 'movePlus1'],
        phases: [{
          atPct: 0.35, job: 'darkKnightRisen', name: 'Brannoc Unbound', heal: 1,
          passives: ['counter', 'magickUp', 'movePlus1'],
          say: 'Brannoc falls to one knee. Then something else stands up in his armour.',
          cry: '"You think this was ever mine to stop?"',
        }],
      },
      { job: 'knight', level: 7, x: 4, y: 4, name: 'Black Guard' },
      { job: 'knight', level: 7, x: 8, y: 4, name: 'Black Guard' },
      { job: 'timeMage', level: 7, x: 6, y: 1, name: 'Chronomancer', passives: ['halfMp', 'regenerator'] },
      { job: 'skeleton', level: 7, x: 3, y: 8, name: 'Risen Guard' },
      { job: 'skeleton', level: 7, x: 9, y: 8, name: 'Risen Guard' },
      { job: 'ninja', level: 7, x: 10, y: 8, name: 'Brannoc\'s Shadow' },
    ],
    gil: 5000,
    outro: [
      'The thing in Brannoc\'s armour comes apart, and for a moment the man is there again, and almost grateful.',
      'Tamsin touches the fallen armour and pulls her hand back. It is cold. Not winter-cold. Something older than winter.',
      'In his hand, the last letter: proof of who fed the war between the princes. It is not signed by either prince. It is stamped with a cog inside a circle.',
      '"The Brass Concord," Tamsin says quietly. "Across the Iron Sea. They sell engines to anyone with a war to lose."',
      'Rowan folds the letter away. "Then the war was never ours. Let us go and find whose it was."',
    ],
  },

  // ---- Act II: the Brass Concord ----
  {
    objective: { type: 'rout', protectLeader: true },
    id: 'ch8', title: 'Smoke on the Coast Road', map: 'fordwater',
    camp: [
      'The letter lies open on the wagon boards. The cog inside the circle looks back at everyone.',
      'Tamsin: "The Concord does not fight wars. It sells them. If it is on our road, it has decided we are bad for business."',
      'Bram: "Then we are doing something right."  Garret: "We are doing something expensive. Same thing, to them."',
    ],
    intro: [
      'Word travels faster than a company on foot. By the time Rowan reaches the coast road, the Concord already knows the name Aldric.',
      'Their scouts wear no prince\'s colours. They wear goggles and brass, and the hounds that run with them were never born.',
      '"Those long guns reach further than my bow," Kael says. "And they do not care how high we stand."',
      '"Then we close on them," Garret says, "or find something to stand behind."',
    ],
    enemies: [
      { job: 'gunner', level: 8, x: 9, y: 2, name: 'Concord Scout' },
      { job: 'gunner', level: 8, x: 10, y: 4, name: 'Concord Scout' },
      { job: 'engineer', level: 8, x: 8, y: 3, name: 'Concord Tinker' },
      { job: 'ironhound', level: 8, x: 7, y: 1 },
      { job: 'ironhound', level: 8, x: 10, y: 6 },
    ],
    gil: 2400,
    recruit: { name: 'Ottilie', job: 'engineer', level: 8 },
    outro: [
      'One of the Concord\'s engineers throws down her spanner before the last hound falls. "Ottilie Marsh. I built those hounds. I did not build them to hunt farmers."',
      '"The Concord pays in scrip and promises. Give me a wage I can spend and I will show you how the machines come apart."',
      'Ottilie the Engineer joins the party!',
    ],
  },
  {
    objective: { type: 'rout', protectLeader: true },
    id: 'ch9', title: 'The Foundry at Ironhold', map: 'ironhold',
    camp: [
      'Ottilie draws a sentinel in the ash with a stick: the boiler, the pistons, the brass. "Here. And here. Lightning, or something heavy, and keep off the front of it."',
      'Kael: "You built these."  Ottilie: "I built them to carry ore. Somebody else taught them to carry a piston into a man."',
    ],
    intro: [
      'Ironhold was a mining town. The Concord bought it in a single afternoon and turned the smelter into a foundry that never cools.',
      '"The sentinels are slow," Ottilie says. "Slow and stupid and wrapped in an inch of brass. Lightning gets through it. So does patience."',
      '"Take the catwalks. Their guns cannot see up through the machinery."',
    ],
    enemies: [
      { job: 'sentinel', level: 8, x: 4, y: 2 },
      { job: 'sentinel', level: 8, x: 7, y: 2 },
      { job: 'gunner', level: 9, x: 9, y: 1, name: 'Foundry Guard' },
      { job: 'gunner', level: 8, x: 9, y: 3, name: 'Foundry Guard' },
      { job: 'engineer', level: 9, x: 5, y: 1, name: 'Foreman' },
    ],
    gil: 2800,
    outro: [
      'The foundry floor falls silent for the first time in a year. In the foreman\'s office, shipping manifests: engines, hounds, sentinels, all bound for Cogsworth Bridge.',
      '"They are not raiding," Rowan says. "They are moving an army across the river."',
    ],
  },
  {
    objective: { type: 'survive', rounds: 5, protectLeader: true },
    id: 'ch10', title: 'Cogsworth Bridge', map: 'cogsworth',
    camp: [
      'Mira: "Five rounds, on a bridge, in the rain, with charges under our feet. Say the plan again so I can hate it properly."',
      'Ottilie: "I find the fuses. You keep them off me. The rain is neither here nor there."  Mira: "The rain is here. It is always here."',
      'Rowan: "Hold the south end. Nobody crosses. Nobody goes north to be a hero."  He is looking at Bram.',
    ],
    intro: [
      'Cogsworth Bridge is the only crossing for forty miles, and the Concord\'s charges are already set beneath it.',
      '"Ottilie needs five rounds to find the fuses," Mira says. "We hold the south end until she does. Whatever comes across."',
      'Something comes across. It does not walk; it drifts down out of the rain on a canvas balloon, and it has a gun.',
    ],
    enemies: [
      { job: 'aeronaut', level: 10, x: 6, y: 1, name: 'Concord Aeronaut' },
      { job: 'gunner', level: 10, x: 4, y: 2, name: 'Bridge Guard' },
      { job: 'gunner', level: 10, x: 8, y: 2, name: 'Bridge Guard' },
      { job: 'sentinel', level: 10, x: 5, y: 3 },
      { job: 'sentinel', level: 10, x: 7, y: 3 },
      { job: 'engineer', level: 10, x: 2, y: 1, name: 'Sapper' },
    ],
    gil: 3200,
    recruit: { name: 'Bastian', job: 'gunner', level: 10 },
    outro: [
      'The fuses come out of the bridge in Ottilie\'s fists. The Concord column, halted on the north bank, does not try again that night.',
      'A deserter from the column wades the shallows with his rifle over his head. "Bastian Reeve. Sergeant of the Marshal\'s guard, until they ordered the bridge blown with our own wounded on it."',
      'Bastian the Gunner joins the party!',
    ],
  },
  {
    objective: { type: 'boss', protectLeader: true },
    id: 'ch11', title: 'The Aether Yards', map: 'aetheryards',
    camp: [
      'Bastian cleans his rifle the way other men pray. "Vexley will have the gantry rigged to lift. If the ship gets up, this was for nothing."',
      'Lysa: "Then it does not get up."  Bastian: "It weighs forty tons."  Lysa: "Then we are efficient about it."',
      'Tamsin, quietly, to Rowan: "The Director will be watching. Let him see what we are."',
    ],
    intro: [
      'The Aether Yards are where the Concord builds its airships, and where Marshal Vexley keeps the only one that flies.',
      '"Vexley does not lose," Bastian says. "He retreats, and calls it a lesson. Do not let him reach the gantry."',
      '"And the Director will be watching from the harbour. Whatever we do here, he will know it before we are done."',
    ],
    enemies: [
      { job: 'gunner', level: 12, x: 6, y: 6, name: 'Marshal Vexley', boss: true, passives: ['counter', 'attackUp', 'movePlus1'] },
      { job: 'aeronaut', level: 11, x: 4, y: 5, name: 'Yard Aeronaut' },
      { job: 'aeronaut', level: 11, x: 8, y: 7, name: 'Yard Aeronaut' },
      { job: 'sentinel', level: 11, x: 6, y: 9 },
      { job: 'engineer', level: 11, x: 10, y: 4, name: 'Dockmaster' },
      { job: 'ironhound', level: 11, x: 10, y: 8 },
    ],
    gil: 3600,
    outro: [
      'Vexley surrenders his pistol on the gantry with the airship burning behind him. "You have cost the Director a season. He will want to speak with you about it. At Brassgate."',
      'Rowan looks across the water at the lights of the Concord\'s city. "Good. I have a letter to return to him."',
    ],
  },
  {
    objective: { type: 'boss', protectLeader: true },
    id: 'ch12', title: 'Brassgate', map: 'brassgate',
    camp: [
      'Rowan turns the letter over in his hands one last time. "He killed my father over a bill of lading."',
      'Garret: "And built a war to hide it. Men like Crane do not think of it as killing. They think of it as a cost."',
      'Ottilie: "There is something in that hall. Something they did not let me near. Whatever it is, it is not a sentinel."',
      'Bram: "Good. I was getting bored of sentinels."',
    ],
    intro: [
      'Brassgate is not a fortress. It is a counting house with walls, and Director Halvard Crane receives Rowan in its great hall like a debtor.',
      '"Two princes, one crown, and a realm that would pay anything to end it. I sold them the anything. I sold it to both."',
      '"Your father worked it out from a bill of lading. I had him killed for arithmetic. Do not take it personally."',
      'Behind the Director, something the size of a house stands with its furnace banked, waiting.',
      'Rowan lays the letter on the counting table. "This is yours. I came to return it."',
    ],
    enemies: [
      { job: 'artificer', level: 14, x: 6, y: 2, name: 'Director Crane', boss: true,
        passives: ['counter', 'magickUp', 'movePlus1'],
        phases: [{
          atPct: 0.4, job: 'colossus', name: 'The Colossus', heal: 1,
          passives: ['counter', 'attackUp', 'movePlus1'],
          say: 'Crane steps backwards into the open chest of the machine behind him, and the machine closes.',
          cry: '"I built a war that runs on time, Aldric. You are simply late."',
        }],
      },
      { job: 'sentinel', level: 11, x: 4, y: 3 },
      { job: 'sentinel', level: 11, x: 8, y: 3 },
      { job: 'gunner', level: 12, x: 3, y: 1, name: 'Director\'s Guard' },
      { job: 'gunner', level: 12, x: 9, y: 1, name: 'Director\'s Guard' },
      { job: 'engineer', level: 12, x: 6, y: 5, name: 'Chief Engineer' },
      { job: 'aeronaut', level: 12, x: 1, y: 6, name: 'Gallery Aeronaut' },
    ],
    gil: 8000,
    outro: [
      'The Colossus sinks to its knees with its furnace gone dark, and the Director climbs out of it a small man in a singed coat.',
      'In the machine\'s chest, where a furnace should be, sits a core of grey metal that gives off cold instead of heat. Ottilie will not touch it. "That is not ours," she says. "That is not anybody\'s."',
      'The Concord\'s ledgers go to both princes at once, with Rowan\'s seal beside the cog. By spring there is nothing left for either to fight about, and everyone knows why.',
      'The last page of the last ledger is a shipping order, paid in a script none of them can read: eleven more cores of star-iron, from somewhere north of the ice.',
      'Rowan Aldric goes home, for a while. The company that walked the road stays together, because that is what it has become, and because the road is not finished.',
      '--- END OF ACT II. The road north is open. ---',
    ],
  },

  // ---- Act III: the Winter Court ----
  {
    objective: { type: 'rout', protectLeader: true },
    id: 'ch13', title: 'The Frost Rider', map: 'rimewater',
    camp: [
      'Bram: "A frozen river. We are going to fight on a frozen river."  Ingrid: "You are going to fight on the parts that hold."',
      'Ottilie has the star-iron core from Brassgate wrapped in three blankets. It is still cold through all of them.',
      'Rowan: "Whatever took Brannoc came from up here. I want to know what it is before it knows we are coming."',
    ],
    intro: [
      'The rider\'s name is Ingrid, and she was a Warden of the north before the north stopped needing wardens.',
      '"The Court took Frostholm in a night," she says. "No fire, no fight. In the morning the people were still there, and they had stopped being cold, and they had stopped being anything else."',
      'She leads the company onto Rimewater, where the river froze mid-current a hundred years ago and never thawed.',
      '"They will come out of the fog. The knights first. The wights after, up out of the ice itself. Do not stand still for long."',
    ],
    enemies: [
      { job: 'hollowKnight', level: 12, x: 10, y: 2 },
      { job: 'hollowKnight', level: 12, x: 11, y: 4 },
      { job: 'rimeWight', level: 12, x: 8, y: 5 },
      { job: 'rimeWight', level: 12, x: 11, y: 6 },
      { job: 'frostweaver', level: 12, x: 11, y: 2, name: 'Court Frostweaver' },
    ],
    gil: 3600,
    recruit: { name: 'Ingrid', job: 'warden', level: 13 },
    outro: [
      'The last wight goes back into the ice it came from. Ingrid pulls her spear out of a hollow knight and looks at what is inside the armour. Nothing is.',
      '"I have been watching the Court for eleven years," she says. "I am done watching."',
      'Ingrid the Warden joins the party!',
    ],
  },
  {
    objective: { type: 'rout', protectLeader: true },
    id: 'ch14', title: 'Frostholm', map: 'frostholm',
    camp: [
      'Kael: "Ingrid says the thralls do not fight unless a knight is near. So we go for the knights."  Garret: "We always go for the knights. It is the one plan that has never let us down."',
      'Mira: "If any of you get taken, I am not carrying you home. I will leave you in the snow and be sad about it later."',
      'Tamsin does not sleep. She sits with the star-iron core and, once, very quietly, tells it no.',
    ],
    intro: [
      'Frostholm is intact. Every door is shut, every chimney cold, and every window has someone standing behind it, not moving.',
      '"They are not dead," Tamsin says. "That is the worst of it. They are waiting for something to tell them what to do."',
      'Something does. The doors open all at once.',
      '"Break the knights that hold them," Ingrid says, "and the thralls may wake."',
    ],
    enemies: [
      { job: 'hollowKnight', level: 13, x: 3, y: 4 },
      { job: 'hollowKnight', level: 12, x: 5, y: 8 },
      { job: 'rimeWight', level: 12, x: 0, y: 5 },
      { job: 'rimeWight', level: 12, x: 8, y: 1 },
      { job: 'frostweaver', level: 13, x: 4, y: 1, name: 'Court Frostweaver' },
      { job: 'squire', level: 12, x: 7, y: 3, name: 'Frostholm Thrall' },
    ],
    gil: 3800,
    outro: [
      'When the last hollow knight falls, the people of Frostholm sit down in the snow where they stand and begin, slowly, to shiver.',
      '"Cold," one of them says, as if he has found the word after a long search. "It is cold."  Lysa wraps him in her own cloak. "Yes. Good. Stay that way."',
      'On the knight\'s breastplate, under the frost, a crest: a crown of icicles over a circle. The Court does not hide its seal.',
    ],
  },
  {
    objective: { type: 'rout', protectLeader: true },
    id: 'ch15', title: 'The Glacier Pass', map: 'glacierpass',
    camp: [
      'Ingrid draws the pass in the snow. "Narrow here. The drake keeps to the left, where the ice is thick. Go right, and go high."',
      'Bram: "Everything up here wants us to go high. I am beginning to feel appreciated."',
      'Ottilie: "The core is colder tonight. Whatever is up there, we are getting closer to it."',
    ],
    intro: [
      'The only road to the Hollow Court climbs the glacier, and the glacier has something living in it.',
      '"An ice drake," Ingrid says. "The Court feeds it. It is the reason no one from Frostholm ever came back down."',
      'Bastian sights along his rifle at a shape moving under the ice. "That is not a drake. That is a river with teeth."',
      '"Then climb," Rowan says. "High ground, and keep the mages behind the shields."',
    ],
    enemies: [
      { job: 'iceDrake', level: 13, x: 5, y: 2 },
      { job: 'hollowKnight', level: 13, x: 2, y: 4 },
      { job: 'hollowKnight', level: 13, x: 8, y: 5 },
      { job: 'frostweaver', level: 14, x: 7, y: 1, name: 'Pass Frostweaver' },
      { job: 'rimeWight', level: 14, x: 3, y: 7 },
    ],
    gil: 4200,
    recruit: { name: 'Eirik', job: 'frostweaver', level: 15 },
    outro: [
      'The drake dies with the pass in its mouth, and the ice goes quiet under their feet for the first time.',
      'One of the Court\'s frostweavers throws down his staff and pulls the hood from a face that is still, just, his own. "Eirik. I was a weaver of the Court because there was no one else to be. I would rather be one of yours."',
      '"The Regent will know. Let him."',
      'Eirik the Frostweaver joins the party!',
    ],
  },
  {
    objective: { type: 'boss', protectLeader: true },
    id: 'ch16', title: 'The Hollow Court', map: 'hollowcourt',
    camp: [
      'Eirik: "The Chamberlain was the first the Cold took. Before there was a Court, there was him, and a crater, and a winter that did not end."',
      'Garret: "So it is old."  Eirik: "It is older than the crown. It is older than the ice."  Garret: "Then it has had long enough."',
      'Rowan looks at the star-iron core one last time. "Tomorrow we give this back."',
    ],
    intro: [
      'The Hollow Court was a palace once, carved into the glacier by people who thought the cold was a god. They were not wrong. They were only early.',
      'Its Chamberlain waits in the throne room with the Court\'s knights around him and a crown of icicles on a head that has not been alive for a long time.',
      '"The Regent is beneath us, at Starfall," Eirik says. "The Chamberlain is the door. There is no other way to him."',
      'The Chamberlain speaks without breath. "Southerners. The Regent will be glad of you. He has been hungry a long while."',
    ],
    enemies: [
      { job: 'hollowKnight', level: 16, x: 6, y: 1, name: 'The Chamberlain', boss: true, passives: ['counter', 'attackUp', 'movePlus1'] },
      { job: 'hollowKnight', level: 15, x: 4, y: 3 },
      { job: 'hollowKnight', level: 15, x: 8, y: 3 },
      { job: 'rimeWight', level: 15, x: 3, y: 5 },
      { job: 'rimeWight', level: 15, x: 9, y: 5 },
      { job: 'frostweaver', level: 15, x: 6, y: 4, name: 'Court Frostweaver' },
    ],
    gil: 4800,
    outro: [
      'The Chamberlain comes apart like Brannoc did, and for a moment there is a face inside the frost, very old, and grateful.',
      'Behind the throne, stairs go down into a light that is not any colour Rowan has a name for.',
      '"Starfall," Ingrid says. "Where it landed. Where it has been eating ever since."',
    ],
  },
  {
    objective: { type: 'boss', protectLeader: true },
    id: 'ch17', title: 'Starfall', map: 'starfall',
    camp: [
      'Nobody sleeps. Bram sharpens a blade that is already sharp, which Lysa points out, which Bram already knows.',
      'Ingrid: "If it takes me, do not stop. Do not come back for me."  Rowan: "We came back for everyone. We are not starting a new policy on the last night."',
      'Ottilie holds the core. "It is warmer. Only a little. I think it knows."  Tamsin: "It knows. Let it."',
    ],
    intro: [
      'The crater at Starfall is a bowl of black glass a mile across. At its centre the star-iron still stands where it fell, and the Winter Regent stands beside it.',
      'He looks like a man. He is dressed like a king. The cold coming off him puts frost on Rowan\'s sword from twenty paces.',
      '"You brought it back," the Regent says, looking at the core in Ottilie\'s arms. "They always bring it back. That is what it is for."',
      '"Wars keep it warm. Brannoc\'s war. The Concord\'s. Yours, if you like. Something has to feed it, and it will not be me."',
      'Rowan sets the core down on the black glass. "Nothing is going to feed it. That is why we came."',
    ],
    enemies: [
      { job: 'winterRegent', level: 15, x: 6, y: 3, name: 'The Winter Regent', boss: true,
        passives: ['counter', 'magickUp', 'movePlus1'],
        phases: [{
          atPct: 0.4, job: 'namelessCold', name: 'The Nameless Cold', heal: 0.5,
          passives: ['counter', 'magickUp', 'movePlus1'],
          say: 'The Regent folds like a coat with nobody in it, and what wore him stands up without a shape.',
          cry: '"You brought it back. You always bring it back."',
        }],
      },
      { job: 'hollowKnight', level: 14, x: 4, y: 4 },
      { job: 'hollowKnight', level: 14, x: 8, y: 4 },
      { job: 'rimeWight', level: 14, x: 3, y: 6 },
      { job: 'frostweaver', level: 14, x: 6, y: 2, name: 'Regent\'s Weaver' },
    ],
    gil: 10000,
    outro: [
      'The Regent falls, and the thing behind him has no shape to fall with. It thins. It goes out of the crater like breath off a window.',
      'The star-iron core in Ottilie\'s arms is only iron now, and only heavy. She drops it, and laughs, and cannot stop for a while.',
      'The Court\'s knights kneel in the black glass and become, one at a time, people who are very cold and very tired, and are allowed to be.',
      'In the spring Frostholm lights its chimneys. Elderon has one king, because the princes could not face the company that ended two wars and a winter, and made peace instead.',
      'Rowan Aldric goes home, and this time means to stay. The road behind him is long. The company that walked it is still a company, and always will be.',
      'A year later a letter comes from Vexley at the Concord. Ships out of Fordwater for the Sunder Isles are not coming back, and the ones that do are worse.',
      '--- END OF ACT III. The sea has begun to give back what it took. ---',
    ],
  },

  // ---- Act IV: the Sunder Sea ----
  {
    objective: { type: 'rout', protectLeader: true },
    id: 'ch18', title: 'The Salt Road', map: 'saltwick',
    camp: [
      'Garret reads Vexley\'s letter for the fourth time. "Warm, cheerful, and not themselves. He underlines cheerful."  Rowan: "He would."',
      'Ottilie has the plain iron core on the wagon bench, and beside it a bell she has cast from a piece of it. She rings it once. It sounds like a bell.',
      'Bram: "A year at home and my hands have gone soft."  Ingrid: "Your hands were never the hard part."',
    ],
    intro: [
      'Saltwick was the Concord\'s harbour for the Isles trade. Its light has been dark for a month, and the ships in its harbour are all ships that came back.',
      'Their crews are on the quays, laughing, in the rain, and do not seem to be getting wet.',
      '"Wreckers," says the woman at the pier with a cutlass across her knees. "They light false fires on the reef and take what runs aground. They used to. Now they do it for the Priory, and they do it smiling."',
      '"Wren Marrow. I had a ship and a crew. The Priory has both. Get me to it and you can have the town."',
      'The wreckers turn, all together, and are still smiling. "Company," one of them says, pleasantly. "We were told you would come."',
    ],
    enemies: [
      { job: 'corsair', level: 18, x: 9, y: 1, name: 'Wrecker' },
      { job: 'corsair', level: 18, x: 6, y: 3, name: 'Wrecker' },
      { job: 'harpooner', level: 18, x: 10, y: 2, name: 'Wrecker Harpooner' },
      { job: 'reefCrab', level: 18, x: 9, y: 5 },
      { job: 'saltPriest', level: 19, x: 7, y: 7, name: 'Priory Cantor' },
    ],
    gil: 5200,
    recruit: { name: 'Wren', job: 'corsair', level: 18 },
    outro: [
      'The wreckers stop smiling when the cantor falls, and then they stop standing, and sit on the quay looking at their hands like men waking on a strange floor.',
      '"They sang to us," one of them says. "Out at the Priory. It was such a warm song."',
      'Wren wipes her cutlass on a wrecker\'s coat. "The Priory took my crew for choir practice. I would like them back. I would like the Prior\'s head in a bag."',
      'Wren the Corsair joins the party!',
    ],
  },
  {
    objective: { type: 'survive', rounds: 5, protectLeader: true },
    id: 'ch19', title: 'The Wreck of the Concord Star', map: 'wreck',
    camp: [
      'Wren draws the reef in spilled beer. "The Star went aground here. Vexley\'s flagship. Whatever the Priory wanted off her, it is still aboard, or they would not still be guarding the wreck."',
      'Lysa: "Guarding it with what?"  Wren: "With the crew."  Lysa: "Oh."',
      'Tamsin sits with Ottilie\'s bell in her lap. "It is quiet," she says. "The core used to hum at me. This does not. I think that is the point of it."',
    ],
    intro: [
      'The Concord Star lies broken on the reef with her deck a fathom above the shallows and her sterncastle above that, and her crew still at their posts.',
      'They have been under the water a month. They come up out of it in their oilskins and their armour, and the water comes up with them.',
      '"Drowned," Wren says, without expression. "Every ship that went out. I know that man. I owe him money."',
      '"The tide is coming in," Rowan says. "Hold the deck until it turns. Nothing else comes up out of the sea at high water."',
      'Something under the hull begins, very slowly, to sing.',
    ],
    enemies: [
      { job: 'drownedKnight', level: 20, x: 6, y: 3, name: 'Drowned Mate' },
      { job: 'drownedKnight', level: 20, x: 9, y: 4, name: 'Drowned Bosun' },
      { job: 'siren', level: 20, x: 8, y: 5 },
      { job: 'siren', level: 20, x: 5, y: 6 },
      { job: 'saltPriest', level: 21, x: 7, y: 2, name: 'Priory Cantor' },
      { job: 'reefCrab', level: 20, x: 10, y: 5 },
    ],
    gil: 5600,
    outro: [
      'The tide turns, and what the sea sent up goes back down into it, slowly, as if reluctant.',
      'In the captain\'s cabin, in a strongbox nailed to the deck, is the twelfth core of star-iron, and a Priory letter thanking the Concord for its delivery.',
      '"They were bringing it here," Ottilie says. "All eleven of the others went north to Brassgate. This one went to the sea. On purpose."',
      'Under the letter, in a different hand: "The star that fell at Starfall was the second. The first is ours, and has been since Tessaly drowned."',
    ],
  },
  {
    objective: { type: 'boss', protectLeader: true },
    id: 'ch20', title: 'The Salt Priory', map: 'priory',
    camp: [
      'Wren: "The Priory sits on a rock a mile out. There is a causeway at low water. The Prior does not leave, and nobody who goes out to him comes back down it unsung."',
      'Eirik listens to the sea for a long time. "It is the same," he says at last. "The thing under the Court. It is under the water now, and the water suits it better."',
      'Rowan: "Then we do what we did at Starfall."  Eirik: "At Starfall it had a shape. Ask the sea for its shape."',
    ],
    intro: [
      'The Salt Priory was built by people who pulled a star out of the sea and thought it had come for them. Their descendants keep it in the chapel, and sing to it, and it has learned the tune.',
      'The Prior meets the company on the chapel steps with the whole choir behind him. He is very kind about it.',
      '"You closed the crater," he says. "You put the Cold out into the wind. Where did you think the wind went? It came to us, and we had a star waiting, and the sea to keep it in."',
      '"It is warm now. It is not hungry anymore, it is only glad. Listen." The choir begins, and one of the novices at the back is not singing.',
      '"Ysolde," she says, to nobody, to the company, "novice of the Priory, and I would like it noted that I never once liked the song."',
    ],
    enemies: [
      { job: 'saltPriest', level: 24, x: 5, y: 2, name: 'The Prior', boss: true, passives: ['magickUp', 'absorbMp', 'movePlus1'] },
      { job: 'saltPriest', level: 22, x: 4, y: 3, name: 'Cantor' },
      { job: 'drownedKnight', level: 23, x: 3, y: 4, name: 'Chapel Warden' },
      { job: 'drownedKnight', level: 23, x: 7, y: 4, name: 'Chapel Warden' },
      { job: 'siren', level: 22, x: 2, y: 2 },
      { job: 'siren', level: 22, x: 8, y: 3 },
    ],
    gil: 6200,
    recruit: { name: 'Ysolde', job: 'tidecaller', level: 20 },
    outro: [
      'The Prior dies mid-verse, still kind, and the choir stops as if a door has shut. Wren finds her crew among them, hoarse and ashamed and alive.',
      'The chapel is empty. Where the star should stand there is a wet stone floor and a hole the shape of the sea.',
      '"It went down," Ysolde says. "The Prior gave it to Tessaly a month ago. To the queen. The drowned one. She has been asking for it for four hundred years, and this month somebody finally said yes."',
      'Ysolde the Tidecaller joins the party!',
    ],
  },
  {
    objective: { type: 'rout', protectLeader: true },
    id: 'ch21', title: 'The Drowned City', map: 'tessaly',
    camp: [
      'Ysolde: "Tessaly drowned in a night, four hundred years ago, with its queen at prayer. The Priory says the sea took it. The Priory does not say the queen asked it to."',
      'Kael: "Low tide bares the streets twice a day. We go in on the ebb and we are out before the flood, or we are part of the city."  Bram: "I have been part of worse places."',
      'Ottilie rings the bell, once, on the beach. Far out, something very large turns over in its sleep.',
    ],
    intro: [
      'At the bottom of the ebb Tessaly stands up out of the sea, street by street: the stumps of houses, the old square, the chapel where the queen still kneels.',
      'Her guard are on their corners as they have been for four hundred years, and they turn their helms towards the company all together, like weathervanes.',
      '"The tide is out for an hour," Ysolde says. "The city knows it. Everything that lives in it is awake."',
      'Something with a spine the length of the square lifts its head over the chapel roof and looks at them with a yellow eye.',
      '"Leviathan," Wren says. "Well. I always wondered what one looked like."',
    ],
    enemies: [
      { job: 'leviathan', level: 25, x: 6, y: 5 },
      { job: 'drownedKnight', level: 24, x: 3, y: 2, name: 'Tessaly Guard' },
      { job: 'drownedKnight', level: 24, x: 9, y: 2, name: 'Tessaly Guard' },
      { job: 'drownedKnight', level: 25, x: 6, y: 1, name: 'Captain of the Watch' },
      { job: 'siren', level: 24, x: 2, y: 6 },
      { job: 'saltPriest', level: 24, x: 10, y: 6, name: 'Drowned Cantor' },
      { job: 'reefCrab', level: 24, x: 4, y: 3 },
    ],
    gil: 6800,
    outro: [
      'The leviathan dies across the square with the tide already licking at its coils, and the guard of Tessaly fall where they stand and do not get up, for the first time in four hundred years.',
      'In the chapel the queen is not at prayer. The floor is open, and stairs go down under the water into a light that is the same colour as the one under the Hollow Court.',
      '"The Tidestone," Ysolde says. "Where the first star lies. The queen has taken the second down to it, and the sea is holding its breath."',
      'It is. The water is going out and out, past any tide, and not coming back.',
    ],
  },
  {
    objective: { type: 'boss', protectLeader: true },
    id: 'ch22', title: 'The Drowned Queen', map: 'tidestone',
    camp: [
      'Nobody sleeps. The sea is a mile out and still going, and the sound of it leaving is the loudest thing any of them has heard.',
      'Wren: "If it takes me, I want it noted that I was owed money."  Rowan: "Noted. We came back for everyone at Starfall. That is still the policy."',
      'Ottilie has the bell in both arms. "At Starfall it could not hold its shape when we broke the thing wearing it. Down there it is wearing the sea. So we give it something else to ring against." Tamsin: "It will hear. Let it."',
    ],
    intro: [
      'The Tidestone is a bowl of black glass at the bottom of the Sunder Sea, bared by a tide that has no business going out this far, and at its centre the first star stands where it fell with the second laid at its foot.',
      'The Drowned Queen of Tessaly kneels between them. She has been kneeling for four hundred years. She stands up.',
      '"You brought it back," she says, and it is not her voice. "They always bring it back."',
      '"The Cold fed on wars. I feed on the sea, and the sea does not end. You cannot starve me here. You cannot put me out into the wind. There is no wind, down here."',
      'Ottilie sets the bell down on the black glass. "No," she says. "But there is this."',
    ],
    enemies: [
      { job: 'drownedQueen', level: 25, x: 6, y: 5, name: 'The Drowned Queen', boss: true,
        passives: ['counter', 'magickUp', 'movePlus1'],
        phases: [{
          atPct: 0.4, job: 'theDeep', name: 'The Deep', heal: 0.5,
          passives: ['counter', 'magickUp', 'movePlus1'],
          say: 'The queen folds like wet cloth, and what wore her stands up out of the glass with the sea for a shape.',
          cry: '"There is no wind down here. There is nothing to put me out into."',
        }],
      },
      { job: 'drownedKnight', level: 24, x: 3, y: 3, name: 'Queen\'s Guard' },
      { job: 'drownedKnight', level: 24, x: 9, y: 3, name: 'Queen\'s Guard' },
      { job: 'siren', level: 24, x: 2, y: 6 },
      { job: 'siren', level: 24, x: 10, y: 6 },
      { job: 'saltPriest', level: 24, x: 6, y: 2, name: 'Queen\'s Cantor' },
      { job: 'leviathan', level: 24, x: 8, y: 9, name: 'The Old Serpent' },
    ],
    gil: 14000,
    outro: [
      'The Deep has no shape to fall with, so it does not fall. It rings. Ottilie\'s bell, cast from the plain iron it left behind, rings against it, and it cannot hold the sea and the sound both.',
      'It goes out of the water the way it went out of the crater, and this time there is no wind to carry it, and no star waiting, and nothing to feed it. It thins, and it is gone.',
      'Two lumps of iron lie on the black glass, plain and heavy. The queen of Tessaly is a small woman in a wet dress who has been kneeling a long time, and is allowed, at last, to lie down.',
      'The sea comes back. It comes back slowly, and kindly, and Wren swears it apologises. The company goes up the stairs ahead of it with the bell between them, and does not look back.',
      'In the spring the Concord\'s ships sail for the Isles and come home, and their crews are exactly as cheerful as they should be. Saltwick lights its lamp. Tessaly stays under the sea, and sleeps.',
      'Rowan Aldric goes home, and does not say "this time", because there is no need: the ice is quiet, the sea is quiet, and nothing is coming that the company has not already met and outlasted. On the last night before the roads part, Ottilie rings the bell once, and listens, and hears nothing at all, and everyone around the fire understands that this is the best sound there is.',
      '--- THE END. Thank you for playing. Trials await at camp, and the wagon carries legendary arms. ---',
    ],
    final: true,
  },
];

// The campaign in acts. The third is groundwork: named, foreshadowed, and not
// yet walkable.
const ACTS = [
  { title: 'The War of Princes', from: 0, to: 6 },
  { title: 'The Brass Concord', from: 7, to: 11 },
  { title: 'The Winter Court', from: 12, to: 16 },
  { title: 'The Sunder Sea', from: 17, to: 21 },
];
// Said of the road once it is walked to the end.
const AFTER_THE_WAR = 'Two wars, a winter and a sea are over. What remains are the trials, and the company.';

// Around the fire once the war is won: what the company says while it trains,
// one line at a time as the trials go by. All of it points north.
const EPILOGUE_CAMP = [
  'The fire is the first anyone has lit north of the ice in a hundred years, and Ingrid keeps feeding it long after it needs feeding.',
  'Ottilie has the star-iron core on the wagon bench, plain iron now. "I am going to make something out of it. Something that carries ore."',
  'Bastian: "Vexley wrote. The Concord is a shipping company again. He says it is very boring and he is very happy."',
  'Lysa has run out of things to count and has started counting the company. She gets a different number each time and does not mind.',
  'Eirik says the aurora is only weather now. He watches it anyway, every night, to be sure.',
  'Garret: "Two wars, a winter and a sea. Your father would have called that a start."  Rowan: "He would have. Let us not tell him what comes next."',
  'Wren has been paid what she was owed, by Vexley, in person, and has not stopped talking about it. Ysolde has taken up singing, and is bad at it, and knows, and does not mind.',
  'The bell hangs from the wagon now. Ottilie rings it at every camp, once, and listens. "Nothing," she says every night, pleased. "Still nothing."',
  'The trials go on because the company likes them. Nobody is paying for them. That, Mira says, is how you can tell they are honest.',
];

// ------------------------------------------------------------------ cities
/* Towns on the road, each held by someone who should not have it. Open one
   with a battle and it stays open: a tavern that hires trained hands, and a
   market that sells what the wagon never carries. Levels rise to meet a party
   that comes late. */
const CITIES = [
  { id: 'redwater', name: 'Redwater', from: 1, pos: [0.93, 0.90], map: 'quarry', level: 2, gil: 900, hireCost: 450,
    held: 'held by the Redwater Reavers', blurb: 'A market town on the quarry road, taken by the guard that was paid to hold it.',
    intro: [
      'Redwater sits on the quarry road with its gates shut and its own guard on the walls, and the guard have decided the town belongs to them now.',
      '"Reavers," Garret says. "They were paid to hold it and nobody came to relieve them. Now they hold it for themselves."',
      '"The quarry is the back door. Take the high stone and they will come down to us."',
    ],
    enemies: [{ job: 'squire', name: 'Reaver' }, { job: 'squire', name: 'Reaver' }, { job: 'archer', name: 'Reaver Archer' }, { job: 'thief', name: 'Reaver Cutpurse' }],
    outro: [
      'The reavers throw down their arms when the last of the high stone falls. Redwater opens its gates that evening, and its market the next morning.',
      'Redwater is open. Its smiths and its tavern are yours to call on.',
    ],
    hires: ['knight', 'archer', 'thief'], stock: ['redwaterSteel', 'reaverCloak'],
    open: 'Smoke from the smithies again, and a tavern that remembers your name.' },
  { id: 'dunmarchTown', name: 'Dunmarch Town', from: 4, pos: [0.34, 0.56], map: 'dunmarch', level: 6, gil: 1300, hireCost: 500,
    held: 'held by the garrison holdouts', blurb: 'The town under the keep, still flying colours nobody pays for.',
    intro: [
      'Dunmarch town still flies Aldous\'s colours from the garrison, though the garrison has not been paid since Brannoc rode for Thornwall.',
      '"Holdouts," Tamsin says. "Good soldiers with no one left to be good for. They will fight because it is what they have."',
    ],
    enemies: [{ job: 'knight', name: 'Holdout Knight' }, { job: 'knight', name: 'Holdout Knight' }, { job: 'whiteMage', name: 'Holdout Priest' }, { job: 'archer', name: 'Holdout Archer' }],
    outro: [
      'The holdouts lay down their arms on the gate steps. The town has been waiting behind them for weeks.',
      'Dunmarch is open. Its chapel trains mages, and its armoury sells what the garrison wore.',
    ],
    hires: ['whiteMage', 'blackMage', 'timeMage'], stock: ['garrisonPlate', 'priestStaff'],
    open: 'The chapel bell rings the hours again. The armoury door stands open.' },
  { id: 'fordwaterTown', name: 'Fordwater', from: 7, pos: [0.62, 0.52], map: 'fordwater', level: 9, gil: 1800, hireCost: 600,
    held: 'held by the Concord customs house', blurb: 'A crossing town taxed to the bone by the Concord\'s customs men and their hounds.',
    intro: [
      'The Concord has a customs house at Fordwater, and the customs house has a garrison, and the garrison has hounds.',
      '"They tax the crossing," Ottilie says. "They tax the road. They would tax the river if they could make it stand still."',
    ],
    enemies: [{ job: 'gunner', name: 'Customs Guard' }, { job: 'gunner', name: 'Customs Guard' }, { job: 'engineer', name: 'Assessor' }, { job: 'ironhound' }],
    outro: [
      'The customs house burns its ledgers before it falls. The town keeps the crossing, and keeps it free.',
      'Fordwater is open. Its workshops hire out engineers and gunners who have had enough of the Concord.',
    ],
    hires: ['engineer', 'gunner'], stock: ['customsPistol', 'ledgerCoat'],
    open: 'The ferry runs for nothing. The workshops have taken down the Concord\'s sign.' },
  { id: 'cogsworthTown', name: 'Cogsworth Town', from: 9, pos: [0.90, 0.50], map: 'cogsworth', level: 11, gil: 2300, hireCost: 700,
    held: 'held by the Concord engine sheds', blurb: 'The town that grew up around the bridge, with sentinels walking its streets.',
    intro: [
      'Cogsworth town grew up around the bridge and the Concord\'s engine sheds. The sheds are still running and the sentinels still walk the streets.',
      '"Nobody in that town has slept through a night in a year," Bastian says. "Let us see if we can fix that."',
    ],
    enemies: [{ job: 'sentinel' }, { job: 'sentinel' }, { job: 'gunner', name: 'Shed Guard' }, { job: 'aeronaut', name: 'Shed Aeronaut' }],
    outro: [
      'The last sentinel winds down in the square, and the town comes out of its houses to look at it.',
      'Cogsworth is open. Its bridgewrights build well, and its aeronauts will fly for coin.',
    ],
    hires: ['aeronaut', 'artificer'], stock: ['bridgewright', 'aetherLantern'],
    open: 'The engine sheds are quiet. Somebody has planted flowers in a sentinel\'s boiler.' },
  { id: 'hearthold', name: 'Hearthold', from: 13, pos: [0.16, 0.26], map: 'rimewater', level: 14, gil: 3000, hireCost: 800,
    held: 'besieged by the Court', blurb: 'The last village on the ice with a fire in it, and the Court has come to put it out.',
    intro: [
      'Hearthold was the last village on the ice with a fire in it. The Court has come to put the fire out.',
      '"They cannot abide a hearth," Ingrid says. "It is the one thing they have never learned to take."',
    ],
    enemies: [{ job: 'hollowKnight' }, { job: 'hollowKnight' }, { job: 'rimeWight' }, { job: 'rimeWight' }, { job: 'frostweaver', name: 'Court Frostweaver' }],
    outro: [
      'The wights go back into the ice and the hearth is still lit. Hearthold keeps it that way.',
      'Hearthold is open. Its wardens and weavers know the north, and its forge remembers fire.',
    ],
    hires: ['warden', 'frostweaver'], stock: ['hearthBlade', 'wardenCloak'],
    open: 'The hearth is lit. It is always lit. Somebody sits up with it all night to be sure.' },
  { id: 'hollowMarket', name: 'The Hollow Market', from: 16, pos: [0.50, 0.26], map: 'hollowcourt', level: 16, gil: 4000, hireCost: 900,
    held: 'held by the Court\'s creatures', blurb: 'The market beneath the Court, where the star-iron was traded for a hundred years.',
    intro: [
      'Beneath the Hollow Court a market once served a people who are mostly gone. The Court\'s creatures have it now, and the star-iron that was traded there.',
      '"Whatever is sold here has been sold to the Cold for a hundred years," Eirik says. "Let us see what it fetches from us."',
    ],
    enemies: [{ job: 'rimeWight' }, { job: 'rimeWight' }, { job: 'hollowKnight' }, { job: 'frostweaver', name: 'Market Weaver' }, { job: 'iceDrake' }],
    outro: [
      'The market is silent when the fighting stops, and then, slowly, it is not.',
      'The Hollow Market is open. Runeblades and artificers wait there, and the last of the star-iron.',
    ],
    hires: ['runeblade', 'samurai'], stock: ['starIronRing', 'auroraStaff'],
    open: 'Lamps in the stalls. The star-iron is sold by weight now, like anything else.' },
  { id: 'saltwick', name: 'Saltwick', from: 17, pos: [0.82, 0.40], map: 'saltwick', level: 18, gil: 4500, hireCost: 950,
    held: 'held by the wreckers', blurb: 'The Concord\'s harbour for the Isles trade, its light dark and its quays full of men who came back wrong.',
    intro: [
      'Saltwick town lies behind the harbour, and the wreckers hold it as they hold the quays: smiling, and in the rain, and dry.',
      '"They have the lighthouse," Wren says. "Nobody has lit it in a month. Every ship that makes for the harbour in the dark goes on the reef, and every crew that swims ashore joins the choir."',
    ],
    enemies: [{ job: 'corsair', name: 'Wrecker' }, { job: 'corsair', name: 'Wrecker' }, { job: 'harpooner', name: 'Wrecker Harpooner' }, { job: 'reefCrab' }, { job: 'saltPriest', name: 'Priory Cantor' }],
    outro: [
      'The light is lit before dark. Half the town climbs the hill to watch it, and the other half stands on the quay and weeps at nothing in particular.',
      'Saltwick is open. Its corsairs and harpooners hire out, and its chandlery sells what the sea trade wore.',
    ],
    hires: ['corsair', 'harpooner'], stock: ['saltwickSabre', 'wreckersCoat'],
    open: 'The light turns all night. Ships come in by it, and their crews are ordinary.' },
  { id: 'tessaly', name: 'Tessaly', from: 20, pos: [0.66, 0.06], map: 'tessaly', level: 21, gil: 5500, hireCost: 1000,
    held: 'held by the drowned', blurb: 'The drowned city, bared for an hour at low water, with its guard still on their corners.',
    intro: [
      'At low water Tessaly\'s market square stands a fathom clear of the sea, and the drowned keep it as they kept it living.',
      '"The stalls are still stocked," Ysolde says. "Four hundred years. The sea kept everything, and the guard kept the sea."',
    ],
    enemies: [{ job: 'drownedKnight', name: 'Tessaly Guard' }, { job: 'drownedKnight', name: 'Tessaly Guard' }, { job: 'siren' }, { job: 'saltPriest', name: 'Drowned Cantor' }, { job: 'leviathan', name: 'Harbour Serpent' }],
    outro: [
      'The guard of the square fall together and the tide, coming in behind the company, does not take them back.',
      'Tessaly is open, for an hour a day. Its tidecallers will follow the company, and its market sells what a queen wore.',
    ],
    hires: ['tidecaller', 'harpooner'], stock: ['queensTrident', 'tessalyPearl'],
    open: 'Open at the ebb. The stallholders are wet, and glad of the custom, and do not talk about the last four hundred years.' },
];

