/* The food dictionary. Everything the scanner can recognise, everything a
   recipe can ask for, and how long each keeps.

   `aliases` are the spellings that appear on packaging, receipts and shelf
   labels; the matcher also tries singular/plural and near-misses, so only
   genuinely different words belong here (brand-ish shorthand such as "OJ",
   receipt abbreviations such as "CHKN BRST"). `days` is a rough fridge or
   cupboard life used for the "use soon" nudge. `staple` marks things a home
   kitchen is assumed to have; recipes never count them as missing unless the
   cook turns that assumption off. */

export const CATEGORIES = {
  produce: 'Produce',
  dairy: 'Dairy & eggs',
  meat: 'Meat & fish',
  grain: 'Grains, pasta & bread',
  pantry: 'Cans, jars & dry goods',
  spice: 'Herbs & spices',
  condiment: 'Oils, sauces & condiments',
  frozen: 'Frozen',
  other: 'Other',
};

// id, name, category, days, aliases, staple
const F = (id, name, category, days, aliases = [], staple = false) => ({ id, name, category, days, aliases, staple });

export const FOODS = [
  // ---- produce
  F('onion', 'Onion', 'produce', 30, ['onions', 'yellow onion', 'brown onion', 'white onion', 'red onion', 'spanish onion']),
  F('garlic', 'Garlic', 'produce', 60, ['garlic bulb', 'garlic cloves']),
  F('shallot', 'Shallot', 'produce', 30, ['shallots']),
  F('spring_onion', 'Spring onion', 'produce', 7, ['scallion', 'scallions', 'green onion', 'green onions']),
  F('leek', 'Leek', 'produce', 10, ['leeks']),
  F('tomato', 'Tomato', 'produce', 7, ['tomatoes', 'vine tomatoes', 'cherry tomatoes', 'plum tomatoes', 'roma tomatoes', 'tomatoe']),
  F('potato', 'Potato', 'produce', 21, ['potatoes', 'russet', 'russet potatoes', 'yukon gold', 'new potatoes', 'baby potatoes', 'red potatoes']),
  F('sweet_potato', 'Sweet potato', 'produce', 21, ['sweet potatoes', 'yam', 'yams']),
  F('carrot', 'Carrot', 'produce', 21, ['carrots', 'baby carrots']),
  F('celery', 'Celery', 'produce', 14, ['celery sticks', 'celery hearts']),
  F('bell_pepper', 'Bell pepper', 'produce', 10, ['bell peppers', 'red pepper', 'green pepper', 'yellow pepper', 'capsicum', 'sweet pepper', 'peppers']),
  F('chili', 'Chili pepper', 'produce', 14, ['chilli', 'chilies', 'chillies', 'jalapeno', 'jalapenos', 'serrano', 'red chili', 'green chili', 'chile', 'chiles']),
  F('cucumber', 'Cucumber', 'produce', 7, ['cucumbers', 'cuke', 'english cucumber']),
  F('zucchini', 'Zucchini', 'produce', 7, ['courgette', 'courgettes', 'zucchinis']),
  F('eggplant', 'Eggplant', 'produce', 7, ['aubergine', 'aubergines', 'eggplants']),
  F('mushroom', 'Mushroom', 'produce', 7, ['mushrooms', 'button mushrooms', 'cremini', 'portobello', 'shiitake', 'chestnut mushrooms']),
  F('broccoli', 'Broccoli', 'produce', 7, ['broccolini', 'broccoli crowns', 'broccoli florets']),
  F('cauliflower', 'Cauliflower', 'produce', 7, []),
  F('cabbage', 'Cabbage', 'produce', 21, ['green cabbage', 'red cabbage', 'savoy cabbage', 'napa cabbage']),
  F('kale', 'Kale', 'produce', 5, ['curly kale', 'cavolo nero']),
  F('spinach', 'Spinach', 'produce', 5, ['baby spinach', 'spinach leaves']),
  F('lettuce', 'Lettuce', 'produce', 7, ['romaine', 'iceberg', 'little gem', 'mixed greens', 'salad greens', 'salad leaves', 'spring mix', 'rocket', 'arugula']),
  F('green_beans', 'Green beans', 'produce', 7, ['french beans', 'string beans', 'haricots verts', 'fine beans']),
  F('peas', 'Peas', 'frozen', 180, ['garden peas', 'frozen peas', 'petit pois', 'sugar snap peas', 'snap peas']),
  F('corn', 'Corn', 'produce', 5, ['sweetcorn', 'sweet corn', 'corn on the cob', 'corn cob', 'corn kernels', 'frozen corn']),
  F('asparagus', 'Asparagus', 'produce', 4, []),
  F('avocado', 'Avocado', 'produce', 5, ['avocados', 'hass avocado']),
  F('lemon', 'Lemon', 'produce', 21, ['lemons']),
  F('lime', 'Lime', 'produce', 21, ['limes']),
  F('orange', 'Orange', 'produce', 14, ['oranges', 'navel oranges', 'clementines', 'mandarins']),
  F('apple', 'Apple', 'produce', 21, ['apples', 'gala', 'granny smith', 'fuji', 'pink lady', 'honeycrisp', 'braeburn']),
  F('banana', 'Banana', 'produce', 5, ['bananas']),
  F('pear', 'Pear', 'produce', 10, ['pears']),
  F('grapes', 'Grapes', 'produce', 7, ['grape', 'red grapes', 'green grapes']),
  F('strawberry', 'Strawberries', 'produce', 4, ['strawberries', 'strawberry']),
  F('blueberry', 'Blueberries', 'produce', 7, ['blueberries', 'blueberry']),
  F('raspberry', 'Raspberries', 'produce', 3, ['raspberries', 'raspberry']),
  F('mango', 'Mango', 'produce', 7, ['mangoes', 'mangos']),
  F('pineapple', 'Pineapple', 'produce', 5, []),
  F('ginger', 'Ginger', 'produce', 21, ['fresh ginger', 'ginger root']),
  F('cilantro', 'Cilantro', 'produce', 5, ['coriander', 'fresh coriander', 'coriander leaves']),
  F('parsley', 'Parsley', 'produce', 7, ['flat leaf parsley', 'fresh parsley']),
  F('basil', 'Basil', 'produce', 5, ['fresh basil', 'basil leaves']),
  F('mint', 'Mint', 'produce', 7, ['fresh mint']),
  F('dill', 'Dill', 'produce', 7, ['fresh dill']),
  F('rosemary', 'Rosemary', 'produce', 14, ['fresh rosemary']),
  F('thyme', 'Thyme', 'produce', 14, ['fresh thyme']),

  // ---- dairy & eggs
  F('egg', 'Eggs', 'dairy', 28, ['eggs', 'large eggs', 'free range eggs', 'dozen eggs', 'egg']),
  F('milk', 'Milk', 'dairy', 7, ['whole milk', 'semi skimmed', 'skimmed milk', '2% milk', 'skim milk', 'oat milk', 'almond milk', 'soy milk']),
  F('butter', 'Butter', 'dairy', 60, ['salted butter', 'unsalted butter', 'butter block']),
  F('cheddar', 'Cheddar', 'dairy', 30, ['cheddar cheese', 'mature cheddar', 'sharp cheddar', 'cheese', 'grated cheese', 'shredded cheese']),
  F('mozzarella', 'Mozzarella', 'dairy', 10, ['fresh mozzarella', 'shredded mozzarella']),
  F('parmesan', 'Parmesan', 'dairy', 60, ['parmigiano', 'parmigiano reggiano', 'grana padano', 'parmesan cheese', 'pecorino']),
  F('feta', 'Feta', 'dairy', 14, ['feta cheese']),
  F('cream_cheese', 'Cream cheese', 'dairy', 14, ['philadelphia', 'soft cheese']),
  F('yogurt', 'Yogurt', 'dairy', 14, ['yoghurt', 'greek yogurt', 'greek yoghurt', 'natural yogurt', 'plain yogurt']),
  F('cream', 'Cream', 'dairy', 7, ['double cream', 'heavy cream', 'whipping cream', 'single cream', 'half and half']),
  F('sour_cream', 'Sour cream', 'dairy', 14, ['soured cream', 'creme fraiche']),
  F('tofu', 'Tofu', 'dairy', 7, ['firm tofu', 'bean curd', 'silken tofu']),

  // ---- meat & fish
  F('chicken_breast', 'Chicken breast', 'meat', 2, ['chicken breasts', 'chicken fillets', 'chicken fillet', 'chkn brst', 'boneless chicken', 'chicken']),
  F('chicken_thigh', 'Chicken thighs', 'meat', 2, ['chicken thigh', 'chicken legs', 'chicken drumsticks', 'drumsticks', 'whole chicken']),
  F('ground_beef', 'Ground beef', 'meat', 2, ['beef mince', 'minced beef', 'mince', 'lean mince', 'hamburger meat', 'ground chuck']),
  F('beef_steak', 'Beef steak', 'meat', 3, ['steak', 'sirloin', 'ribeye', 'rump steak', 'flank steak', 'stewing beef', 'beef']),
  F('pork_chop', 'Pork chops', 'meat', 3, ['pork chop', 'pork loin', 'pork tenderloin', 'pork', 'pork shoulder']),
  F('ground_pork', 'Ground pork', 'meat', 2, ['pork mince', 'minced pork']),
  F('sausage', 'Sausages', 'meat', 3, ['sausage', 'pork sausages', 'chorizo', 'bratwurst', 'italian sausage']),
  F('bacon', 'Bacon', 'meat', 7, ['streaky bacon', 'back bacon', 'bacon rashers', 'pancetta', 'lardons']),
  F('ham', 'Ham', 'meat', 5, ['sliced ham', 'cooked ham', 'prosciutto', 'deli ham']),
  F('lamb', 'Lamb', 'meat', 3, ['lamb chops', 'lamb mince', 'minced lamb', 'lamb shoulder', 'leg of lamb']),
  F('salmon', 'Salmon', 'meat', 2, ['salmon fillet', 'salmon fillets', 'smoked salmon']),
  F('white_fish', 'White fish', 'meat', 2, ['cod', 'haddock', 'tilapia', 'pollock', 'sea bass', 'fish fillets', 'fish']),
  F('shrimp', 'Shrimp', 'meat', 2, ['prawns', 'king prawns', 'prawn', 'shrimps']),
  F('tuna', 'Canned tuna', 'pantry', 720, ['tuna', 'tinned tuna', 'tuna in water', 'tuna in oil', 'tuna chunks']),

  // ---- grains, pasta & bread
  F('rice', 'Rice', 'grain', 720, ['basmati', 'basmati rice', 'jasmine rice', 'long grain rice', 'white rice', 'brown rice', 'arborio', 'risotto rice', 'sushi rice']),
  F('pasta', 'Pasta', 'grain', 720, ['spaghetti', 'penne', 'fusilli', 'rigatoni', 'linguine', 'tagliatelle', 'macaroni', 'farfalle', 'orzo', 'fettuccine', 'lasagne sheets', 'lasagna noodles']),
  F('noodles', 'Noodles', 'grain', 360, ['egg noodles', 'rice noodles', 'ramen', 'udon', 'soba', 'instant noodles']),
  F('bread', 'Bread', 'grain', 4, ['loaf', 'sliced bread', 'sourdough', 'baguette', 'white bread', 'wholemeal bread', 'whole wheat bread', 'ciabatta', 'rolls', 'bread rolls', 'buns', 'burger buns']),
  F('tortilla', 'Tortillas', 'grain', 14, ['tortilla', 'flour tortillas', 'corn tortillas', 'wraps', 'wrap']),
  F('pita', 'Pita bread', 'grain', 5, ['pitta', 'pita', 'pitta bread', 'flatbread', 'flatbreads', 'naan']),
  F('flour', 'Flour', 'pantry', 365, ['plain flour', 'all purpose flour', 'ap flour', 'self raising flour', 'bread flour', 'wholemeal flour'], true),
  F('oats', 'Oats', 'grain', 365, ['porridge oats', 'rolled oats', 'oatmeal', 'quick oats']),
  F('quinoa', 'Quinoa', 'grain', 365, []),
  F('couscous', 'Couscous', 'grain', 365, []),
  F('breadcrumbs', 'Breadcrumbs', 'pantry', 180, ['panko', 'bread crumbs']),
  F('cornflour', 'Cornstarch', 'pantry', 365, ['cornstarch', 'corn starch', 'corn flour'], true),

  // ---- cans, jars & dry goods
  F('canned_tomato', 'Canned tomatoes', 'pantry', 720, ['chopped tomatoes', 'tinned tomatoes', 'diced tomatoes', 'crushed tomatoes', 'tomato passata', 'passata', 'whole peeled tomatoes', 'san marzano']),
  F('tomato_paste', 'Tomato paste', 'pantry', 365, ['tomato puree', 'tomato purée', 'concentrated tomato']),
  F('chickpeas', 'Chickpeas', 'pantry', 720, ['garbanzo', 'garbanzo beans', 'chick peas', 'canned chickpeas']),
  F('black_beans', 'Black beans', 'pantry', 720, ['canned black beans', 'turtle beans']),
  F('kidney_beans', 'Kidney beans', 'pantry', 720, ['red kidney beans', 'canned kidney beans']),
  F('white_beans', 'White beans', 'pantry', 720, ['cannellini', 'cannellini beans', 'butter beans', 'navy beans', 'haricot beans', 'great northern beans']),
  F('baked_beans', 'Baked beans', 'pantry', 720, ['beans in tomato sauce']),
  F('lentils', 'Lentils', 'pantry', 720, ['red lentils', 'green lentils', 'brown lentils', 'puy lentils', 'split lentils', 'dal', 'dhal']),
  F('coconut_milk', 'Coconut milk', 'pantry', 720, ['coconut cream', 'tinned coconut milk', 'canned coconut milk']),
  F('stock', 'Stock', 'pantry', 365, ['chicken stock', 'vegetable stock', 'beef stock', 'stock cubes', 'stock cube', 'bouillon', 'broth', 'chicken broth', 'vegetable broth', 'beef broth', 'stock pot'], true),
  F('peanut_butter', 'Peanut butter', 'pantry', 180, ['pb', 'crunchy peanut butter', 'smooth peanut butter']),
  F('honey', 'Honey', 'pantry', 720, ['runny honey', 'clear honey']),
  F('sugar', 'Sugar', 'pantry', 720, ['granulated sugar', 'caster sugar', 'brown sugar', 'white sugar', 'icing sugar', 'powdered sugar', 'demerara'], true),
  F('maple_syrup', 'Maple syrup', 'pantry', 365, ['maple']),
  F('nuts', 'Nuts', 'pantry', 180, ['almonds', 'walnuts', 'cashews', 'peanuts', 'pecans', 'pine nuts', 'mixed nuts', 'hazelnuts', 'pistachios']),
  F('seeds', 'Seeds', 'pantry', 180, ['sesame seeds', 'pumpkin seeds', 'sunflower seeds', 'chia seeds', 'flaxseed', 'sesame']),
  F('raisins', 'Raisins', 'pantry', 365, ['sultanas', 'dried cranberries', 'dried fruit', 'dates', 'dried apricots']),
  F('olives', 'Olives', 'pantry', 180, ['black olives', 'green olives', 'kalamata']),
  F('capers', 'Capers', 'pantry', 365, []),
  F('pickles', 'Pickles', 'pantry', 365, ['gherkins', 'dill pickles', 'pickled cucumbers']),
  F('baking_powder', 'Baking powder', 'pantry', 365, ['baking soda', 'bicarbonate of soda', 'bicarb'], true),
  F('cocoa', 'Cocoa powder', 'pantry', 365, ['cocoa', 'cacao', 'dark chocolate', 'chocolate chips', 'chocolate']),
  F('vanilla', 'Vanilla extract', 'pantry', 720, ['vanilla', 'vanilla essence'], true),
  F('coffee', 'Coffee', 'pantry', 180, ['ground coffee', 'coffee beans', 'instant coffee', 'espresso']),
  F('tea', 'Tea', 'pantry', 365, ['tea bags', 'teabags', 'green tea', 'black tea', 'earl grey', 'chamomile']),

  // ---- oils, sauces & condiments
  F('olive_oil', 'Olive oil', 'condiment', 365, ['extra virgin olive oil', 'evoo', 'virgin olive oil'], true),
  F('vegetable_oil', 'Cooking oil', 'condiment', 365, ['vegetable oil', 'sunflower oil', 'canola oil', 'rapeseed oil', 'oil', 'cooking oil', 'peanut oil', 'coconut oil'], true),
  F('sesame_oil', 'Sesame oil', 'condiment', 365, ['toasted sesame oil']),
  F('vinegar', 'Vinegar', 'condiment', 720, ['white vinegar', 'white wine vinegar', 'red wine vinegar', 'apple cider vinegar', 'cider vinegar', 'balsamic', 'balsamic vinegar', 'rice vinegar', 'malt vinegar'], true),
  F('soy_sauce', 'Soy sauce', 'condiment', 365, ['soya sauce', 'light soy', 'dark soy', 'tamari', 'shoyu']),
  F('fish_sauce', 'Fish sauce', 'condiment', 365, ['nam pla']),
  F('oyster_sauce', 'Oyster sauce', 'condiment', 365, []),
  F('hot_sauce', 'Hot sauce', 'condiment', 365, ['sriracha', 'tabasco', 'chili sauce', 'chilli sauce', 'sambal', 'harissa', 'gochujang']),
  F('mustard', 'Mustard', 'condiment', 365, ['dijon', 'dijon mustard', 'wholegrain mustard', 'english mustard', 'yellow mustard']),
  F('mayonnaise', 'Mayonnaise', 'condiment', 90, ['mayo', 'hellmanns', 'aioli']),
  F('ketchup', 'Ketchup', 'condiment', 180, ['tomato ketchup', 'catsup']),
  F('bbq_sauce', 'BBQ sauce', 'condiment', 180, ['barbecue sauce', 'barbeque sauce']),
  F('worcestershire', 'Worcestershire sauce', 'condiment', 720, ['worcester sauce', 'lea and perrins']),
  F('curry_paste', 'Curry paste', 'condiment', 180, ['thai curry paste', 'red curry paste', 'green curry paste', 'massaman paste', 'tikka paste']),
  F('pesto', 'Pesto', 'condiment', 30, ['green pesto', 'red pesto', 'basil pesto']),
  F('salsa', 'Salsa', 'condiment', 30, ['tomato salsa']),
  F('tahini', 'Tahini', 'condiment', 180, []),
  F('miso', 'Miso', 'condiment', 365, ['miso paste', 'white miso', 'red miso']),
  F('white_wine', 'White wine', 'condiment', 5, ['dry white wine', 'sauvignon blanc', 'pinot grigio', 'chardonnay']),
  F('red_wine', 'Red wine', 'condiment', 5, ['merlot', 'cabernet', 'shiraz', 'rioja']),

  // ---- herbs & spices (dried)
  F('salt', 'Salt', 'spice', 9999, ['sea salt', 'table salt', 'kosher salt', 'flaky salt'], true),
  F('black_pepper', 'Black pepper', 'spice', 9999, ['pepper', 'peppercorns', 'ground pepper', 'cracked pepper'], true),
  F('cumin', 'Cumin', 'spice', 720, ['ground cumin', 'cumin seeds']),
  F('coriander_seed', 'Ground coriander', 'spice', 720, ['coriander seeds', 'coriander powder']),
  F('paprika', 'Paprika', 'spice', 720, ['smoked paprika', 'sweet paprika']),
  F('chili_powder', 'Chili powder', 'spice', 720, ['chilli powder', 'cayenne', 'cayenne pepper', 'chili flakes', 'chilli flakes', 'red pepper flakes', 'crushed red pepper']),
  F('curry_powder', 'Curry powder', 'spice', 720, ['garam masala', 'madras curry powder', 'tandoori spice']),
  F('turmeric', 'Turmeric', 'spice', 720, ['ground turmeric', 'haldi']),
  F('cinnamon', 'Cinnamon', 'spice', 720, ['ground cinnamon', 'cinnamon sticks']),
  F('nutmeg', 'Nutmeg', 'spice', 720, ['ground nutmeg']),
  F('oregano', 'Oregano', 'spice', 720, ['dried oregano', 'italian seasoning', 'italian herbs', 'mixed herbs', 'herbes de provence']),
  F('dried_thyme', 'Dried thyme', 'spice', 720, []),
  F('bay_leaf', 'Bay leaves', 'spice', 720, ['bay leaf', 'bay']),
  F('garlic_powder', 'Garlic powder', 'spice', 720, ['garlic granules', 'onion powder']),
  F('ginger_powder', 'Ground ginger', 'spice', 720, ['ginger powder']),
  F('five_spice', 'Five spice', 'spice', 720, ['chinese five spice', 'star anise']),
  F('cardamom', 'Cardamom', 'spice', 720, ['cardamom pods', 'ground cardamom']),
  F('mustard_seed', 'Mustard seeds', 'spice', 720, ['black mustard seeds', 'yellow mustard seeds']),

  // ---- frozen & other
  F('frozen_veg', 'Frozen mixed vegetables', 'frozen', 365, ['mixed vegetables', 'mixed veg', 'frozen vegetables', 'stir fry mix', 'stir fry vegetables']),
  F('frozen_berries', 'Frozen berries', 'frozen', 365, ['mixed berries', 'frozen fruit', 'summer fruits']),
  F('puff_pastry', 'Puff pastry', 'frozen', 180, ['pastry', 'shortcrust pastry', 'pie crust', 'filo', 'phyllo']),
  F('frozen_spinach', 'Frozen spinach', 'frozen', 365, ['chopped spinach']),
  F('ice_cream', 'Ice cream', 'frozen', 90, ['icecream', 'gelato', 'vanilla ice cream']),
  F('hummus', 'Hummus', 'other', 7, ['houmous', 'hommus']),
  F('jam', 'Jam', 'pantry', 365, ['strawberry jam', 'raspberry jam', 'marmalade', 'preserves', 'jelly']),
  F('crackers', 'Crackers', 'pantry', 180, ['rice cakes', 'oatcakes', 'water biscuits']),
  F('juice', 'Juice', 'other', 7, ['orange juice', 'oj', 'apple juice', 'cranberry juice']),
  // ---- more cheese, so "cheese" alone is cheddar but a named cheese is itself
  F('cottage_cheese', 'Cottage cheese', 'dairy', 10, []),
  F('ricotta', 'Ricotta', 'dairy', 7, []),
  F('halloumi', 'Halloumi', 'dairy', 30, ['haloumi', 'grilling cheese']),
  F('brie', 'Brie', 'dairy', 14, ['camembert']),
  F('goat_cheese', 'Goat cheese', 'dairy', 14, ['goats cheese', 'chevre']),
  F('paneer', 'Paneer', 'dairy', 10, []),
  F('blue_cheese', 'Blue cheese', 'dairy', 21, ['stilton', 'gorgonzola', 'roquefort']),

  // ---- more meat & fish
  F('turkey', 'Turkey', 'meat', 3, ['turkey breast', 'turkey mince', 'ground turkey', 'deli turkey', 'sliced turkey']),
  F('hot_dogs', 'Hot dogs', 'meat', 7, ['hot dog', 'frankfurters', 'frankfurter', 'wieners']),
  F('meatballs', 'Meatballs', 'meat', 2, ['meatball']),
  F('sardines', 'Canned sardines', 'pantry', 720, ['sardines', 'sardine', 'tinned sardines', 'mackerel', 'tinned mackerel']),
  F('anchovies', 'Anchovies', 'pantry', 365, ['anchovy', 'anchovy fillets']),
  F('fish_fingers', 'Fish fingers', 'frozen', 365, ['fish sticks', 'breaded fish']),
  F('chicken_nuggets', 'Chicken nuggets', 'frozen', 365, ['nuggets', 'chicken goujons', 'chicken tenders']),

  // ---- more produce
  F('kiwi', 'Kiwi', 'produce', 14, ['kiwis', 'kiwi fruit']),
  F('peach', 'Peach', 'produce', 5, ['peaches', 'nectarine', 'nectarines', 'apricot', 'apricots']),
  F('plum', 'Plum', 'produce', 5, ['plums']),
  F('cherry', 'Cherries', 'produce', 5, ['cherries']),
  F('melon', 'Melon', 'produce', 7, ['watermelon', 'cantaloupe', 'honeydew', 'galia melon']),
  F('grapefruit', 'Grapefruit', 'produce', 14, ['grapefruits']),
  F('pomegranate', 'Pomegranate', 'produce', 14, ['pomegranates', 'pomegranate seeds']),
  F('coconut', 'Coconut', 'pantry', 180, ['desiccated coconut', 'coconut flakes', 'shredded coconut']),
  F('radish', 'Radish', 'produce', 10, ['radishes']),
  F('beetroot', 'Beetroot', 'produce', 21, ['beet', 'beets', 'cooked beetroot']),
  F('parsnip', 'Parsnip', 'produce', 21, ['parsnips']),
  F('turnip', 'Turnip', 'produce', 21, ['turnips', 'swede', 'rutabaga']),
  F('squash', 'Squash', 'produce', 30, ['butternut squash', 'butternut', 'pumpkin', 'acorn squash', 'winter squash']),
  F('brussels_sprouts', 'Brussels sprouts', 'produce', 10, ['brussel sprouts', 'sprouts']),
  F('fennel', 'Fennel', 'produce', 10, ['fennel bulb']),
  F('bok_choy', 'Bok choy', 'produce', 5, ['pak choi', 'pak choy', 'choy sum']),
  F('chard', 'Chard', 'produce', 5, ['swiss chard', 'rainbow chard']),
  F('artichoke', 'Artichoke', 'produce', 7, ['artichokes', 'artichoke hearts']),
  F('edamame', 'Edamame', 'frozen', 365, ['soy beans', 'soya beans']),
  F('sauerkraut', 'Sauerkraut', 'pantry', 90, []),
  F('kimchi', 'Kimchi', 'pantry', 90, []),
  F('tempeh', 'Tempeh', 'dairy', 10, []),

  // ---- bakery, cereals & grains
  F('bagel', 'Bagels', 'grain', 5, ['bagels']),
  F('croissant', 'Croissants', 'grain', 3, ['croissants', 'pastries', 'danish pastry']),
  F('english_muffin', 'English muffins', 'grain', 5, ['english muffin', 'crumpets', 'crumpet', 'muffins']),
  F('cereal', 'Cereal', 'grain', 180, ['breakfast cereal', 'cornflakes', 'corn flakes', 'muesli', 'bran flakes', 'weetabix', 'cheerios']),
  F('granola', 'Granola', 'grain', 180, []),
  F('polenta', 'Polenta', 'grain', 365, ['cornmeal', 'corn meal', 'grits']),
  F('barley', 'Barley', 'grain', 365, ['pearl barley', 'bulgur', 'bulgur wheat', 'freekeh', 'farro']),
  F('yeast', 'Yeast', 'pantry', 365, ['dried yeast', 'instant yeast', 'active dry yeast'], true),

  // ---- snacks, drinks & sauces
  F('tortilla_chips', 'Tortilla chips', 'pantry', 90, ['corn chips', 'nachos', 'crisps', 'potato chips', 'chips']),
  F('popcorn', 'Popcorn', 'pantry', 180, ['popping corn']),
  F('beer', 'Beer', 'other', 180, ['lager', 'ale', 'ipa', 'stout', 'cider']),
  F('sparkling_water', 'Sparkling water', 'other', 365, ['soda water', 'seltzer', 'tonic water', 'mineral water', 'soda', 'cola', 'lemonade']),
  F('salad_dressing', 'Salad dressing', 'condiment', 90, ['ranch dressing', 'ranch', 'caesar dressing', 'vinaigrette', 'french dressing', 'dressing']),
  F('gravy', 'Gravy', 'pantry', 365, ['gravy granules', 'gravy mix']),
  F('canned_soup', 'Canned soup', 'pantry', 720, ['tinned soup', 'soup', 'tomato soup', 'chicken soup']),
  F('pasta_sauce', 'Pasta sauce', 'pantry', 365, ['marinara', 'marinara sauce', 'tomato sauce', 'arrabbiata', 'bolognese sauce', 'pizza sauce']),
  F('cranberry_sauce', 'Cranberry sauce', 'pantry', 365, []),
  F('horseradish', 'Horseradish', 'condiment', 180, ['horseradish sauce', 'wasabi']),
  F('nori', 'Nori', 'pantry', 365, ['seaweed', 'sushi seaweed']),
  F('ghee', 'Ghee', 'condiment', 365, ['lard', 'shortening', 'dripping']),
  F('frozen_pizza', 'Frozen pizza', 'frozen', 180, ['pizza']),
  F('dumplings', 'Dumplings', 'frozen', 180, ['gyoza', 'wontons', 'potstickers', 'spring rolls', 'spring roll']),
  F('ice_lolly', 'Ice lollies', 'frozen', 365, ['ice lollies', 'popsicles', 'popsicle']),
  F('custard', 'Custard', 'dairy', 5, ['custard powder']),
  F('apple_sauce', 'Apple sauce', 'pantry', 365, ['applesauce']),
  F('chocolate_spread', 'Chocolate spread', 'pantry', 365, ['nutella', 'hazelnut spread']),
];


export const FOOD_BY_ID = Object.fromEntries(FOODS.map(f => [f.id, f]));
